version: '3.0'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --mysql-native-password=ON
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${DB_DEFAULT}
